### ISSUE TITLE
Add an interface defining what is a table

### ISSUE THREAD

**Issue by astragier** [squashql/squashql-codegen#2]
We'd like to have a type for the tables in order to use methods on them whatever the table is.
But we still want to access the individual fields. 

Proposal:
```
export interface ITable {
  readonly _name: string;
  getTableFields: () => TableField[];
}

class Product implements ITable {
  readonly _name: string = "product";
  readonly productKey = new TableField("product.product_key");
  readonly productName = new TableField("product.product_name");
  getTableFields: () => TableField[] = () => [
    this.productKey,
    this.productName,
  ];
}
```

Mercio use: we define a query graph schema to compute the queries optimally (it is a base table with the joined tables and their join condition). Instead of givin the table names \+ all the fields and risking to forget one, it would be better to pass the whole table direclty.

**Comment by paulbares** [comment]
Fixes by https://github.com/squashql/squashql-codegen/commit/3f87cff97ed6f815f2ebfe698974e5885abb8c09, available from 1.0.4 onwards.
