### ISSUE TITLE
Remove explicit typing of `_name` properties

### ISSUE THREAD

**Issue by fmo-dev** [squashql/squashql-codegen#3]
In our application we have some cases where we want to use the name of the tables for strict typing, but as they are explicitly typed as `string` it is not possible. 

### Use case 
```
type CurrentPrice = typeof tables.currentPrice._name;
type Product = typeof tables.product._name;
type Store = typeof tables.store._name;

export type StrategyScopeTable = Product | Store | CurrentPrice
```

We need the `_name`  properties to keep the implict typing (as readonly string value) so they can only be equal to one specific value and be usable for strict typing

**Comment by paulbares** [comment]
Fixes by https://github.com/squashql/squashql-codegen/commit/3f87cff97ed6f815f2ebfe698974e5885abb8c09, available from 1.0.4 onwards.
